update property_value set property_value='5.0.10' where property_id= (select property_id from property_info where property_name = 'coreVersionText');

delete fusion_menu_Access_Control where Access_Control_Name = 'SYSTEM_PROPERTIES' and Fusion_Menu_Link_Id = (select Fusion_Menu_Link_Id from Fusion_Menu_Link where Menu_Link_Id = 'integration' and fusion_menu_id= (select fusion_menu_id from fusion_menu where fusion_menu_name='ADMIN_CONSOLE'));
delete fusion_menu_link where Menu_Link_Id = 'integration' and Fusion_Menu_Id = (select Fusion_Menu_Id from fusion_menu where Fusion_Menu_Name='ADMIN_CONSOLE');

update property_info set Property_Desc = 'Defines the Source type from which the employees are to be imported into Exterro Platform' where Property_Name = 'configuration.type' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'Defines the Source type from which the data sources are to be imported into Exterro Platform' where Property_Name = 'configuration.type' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'asset'));
update property_info set Property_Desc = 'Defines the Source type from which matters are to be imported into Exterro Platform' where Property_Name = 'configuration.type' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'matterMgmt'));
update property_info set Property_Desc = 'Defines the Source type from which the matters are to be imported into Exterro Platform' where Property_Name = 'configuration.type' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'matter'));
update property_info set Property_Desc = 'The location that contains the file which consists of the datasources to be inserted into Exterro Platform' where Property_Name = 'configuration.file' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'asset'));
update property_info set Property_Desc = 'Defines the type of datasources to be imported into Exterro Platform' where Property_Name = 'INTEGRATION_DATASOURCE_TYPE' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'asset'));
update property_info set Property_Desc = 'Updates the existing matters in Exterro Platform' where Property_Name = 'update.existing.matters' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'matterMgmt'));
update property_info set Property_Desc = 'Denotes the number of employees to be processed' where Property_Name = 'number.of.custodians.to.process' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'Denotes the number of failed employees to be processed' where Property_Name = 'number.of.failed.custodians.to.process' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'By default employee data source(s) will be added through integration' where Property_Name = 'process.medias' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'Effective date source value to track the employee history' where Property_Name = 'effective.date.source' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));

update property_info set Property_Display_Name = 'No of employees to process' where Property_Name = 'number.of.custodians.to.process' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Display_Name = 'No of failed employees to process' where Property_Name = 'number.of.failed.custodians.to.process' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.1',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'KEY_WORD' , 'Key Word' , 'Key Word' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'OPEN_OFFICES' , 'OPEN OFFICES' , 'OPEN OFFICES' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CAPS_EMAILS' , 'EMAILS' , 'EMAILS' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CAPS_OTHERS' , 'OTHERS' , 'OTHERS' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_TO_START_PRODUCTION_SET_PRIV_MSG' , 'One or more privileged files are added to the production set. Are you sure you want to start the production set?' , 'One or more privileged files are added to the production set. Are you sure you want to start the production set?' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_JOB_HAS_BEEN_RESTARTED' , 'The Job has been restarted.' , 'The Job has been restarted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_SELECTED_JOBS_HAVE_BEEN_RESTARTED' , 'The selected Jobs have been restarted.' , 'The selected Jobs have been restarted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_APPLICABLE_JOBS_HAVE_BEEN_RESTARTED' , 'The applicable Jobs have been restarted.' , 'The applicable Jobs have been restarted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_JOB_HAS_BEEN_DELETED' , 'The Job has been deleted.' , 'The Job has been deleted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_SELECTED_JOBS_HAVE_BEEN_DELETED' , 'The selected Jobs have been deleted.' , 'The selected Jobs have been deleted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'THE_APPLICABLE_JOBS_HAVE_BEEN_DELETED' , 'The applicable Jobs have been deleted.' , 'The applicable Jobs have been deleted.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_NAME_ALREADY_EXISTS' , 'Deliverable with the same name already exists in this activity. Provide a different name.' , 'Deliverable with the same name already exists in this activity. Provide a different name.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.2',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CREATE_PLAN' , 'Create Plan' , 'Create Plan' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECTED_FILES_ARE_ALREADY_EXISTING_IN_THE_CATEGORY' , 'The selected files are already existing in the Category.' , 'The selected files are already existing in the Category.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.3',CURRENT_TIMESTAMP);

update property_info set Property_Desc = 'By default employee data sources will be added through integration' where Property_Name = 'process.medias' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.4',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CREATE_FILE_PROPERTY' , 'Create new file property' , 'Create new file property' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SAVE_FILE_PROPERTY' , 'Save file property' , 'Save file property' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELETE_PROPERTY' , 'Delete Property' , 'Delete Property' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'COLLECTION_FILTER' , 'Collection Filter' , 'Collection Filter' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECT_REQUESTOR' , 'Select Requestor' , 'Select Requestor' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

Update Fusion_New_Label set Label_Display_Value = 'Are you sure you want to delete this redaction reason?' WHERE label_key = 'REDACTION_REASON_DELETE_CONFIRM' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'messages');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.5',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CANCEL_REQUEST' , 'Cancel request' , 'Cancel request' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'MATTER_NAME_CAMEL_CASE' , 'Matter Name' , 'Matter Name' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'COLLECTION_STATUS' , 'Collection Status' , 'Collection Status' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'COLLECTION_FILE_COUNT' , 'Collection File Count' , 'Collection File Count' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CREATED_BY_ASSOCIATION' , 'Created by Association' , 'Created by Association' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'KEY_CUSTODIAN_CAMEL_CASE' , 'Key Custodian' , 'Key Custodian' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'EMPLOYMENT_STATUS_CAMEL_CASE' , 'Employment Status' , 'Employment Status' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DATA_SOURCE_TYPE_CUSTODIAN' , 'Data Source Type' , 'Data Source Type' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'FILE_SIZE_CAMEL_CASE' , 'File Size' , 'File Size' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DESCRIPTION_ADDED_BY' , 'Description Added By' , 'Description Added By' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'APPLIED_LABELS_CAMEL_CASE' , 'Applied Label(s)' , 'Applied Label(s)' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'MODIFIED_EXTENSION' , 'Modified Extension' , 'Modified Extension' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'JOB_STATUS_CAMEL_CASE' , 'Job Status' , 'Job Status' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'JOB_ID_CAMEL_CASE' , 'Job Id' , 'Job Id' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ELAPSED_TIME_HRS' , 'Elasped Time(hh:mm)' , 'Elasped Time(hh:mm)' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'PERCENTAGE_COMPLETED' , 'Percentage completed' , 'Percentage completed' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SERVICE_TYPE_CAMEL_CASE' , 'Service Type' , 'Service Type' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'COLLECTION_CENTER_CAMEL_CASE' , 'Collection Center' , 'Collection Center' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'IP_ADDRES_CAMEL_CASE' , 'IP Address' , 'IP Address' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'MACHINE_NAME_CAMEL_CASE' , 'Machine Name' , 'Machine Name' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'PREDICTIVE_MODEL_NAME_CAMEL_CASE' , 'Predictive Model Name' , 'Predictive Model Name' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SAMPLE_FILES_CAMEL_CASE' , 'Sample Files' , 'Sample Files' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ASSOCIATED_FILES_CAMEL_CASE' , 'Associated Files' , 'Associated Files' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SAMPLE_SET_NAME' , 'Sample Set Name' , 'Sample Set Name' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'RESPONSIVE_THRESHOLD' , 'Responsive Threshold' , 'Responsive Threshold' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CONCEPT_ENGINE' , 'Concept Engine' , 'Concept Engine' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'REQUEST_CANCELLED' , 'The request ''<project name>'' has been canceled.' , 'The request ''<project name>'' has been canceled.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'NO_RECORD_TO_UPLOAD' , 'The file that you are trying to upload has no record.' , 'The file that you are trying to upload has no record.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'WANT_TO_CANCEL_REQUEST' , 'Are you sure you want to cancel the request, <Project Name>?' , 'Are you sure you want to cancel the request, <Project Name>?' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

update notification_email set email_body_to='<html><body style ="font-family:arial;font-size:11pt;"><table width="100%" style="font-family:arial;font-size:11pt;margin-top:5px;"><tr><td valign="top">Custodian List:</td></tr><tr height="10px"><td></td></tr><tr><td valign="top"><table cellpadding="2" border="1" cellspacing="2" width="100%" style="font-family:arial;font-size:11pt;border:1px solid grey;"><tr><td width="20%"><b>Last Name</b></td><td width="20%"><b>First Name</b></td><td width="10%"><b>GUID</b></td><td width="15%"><b>Title</b></td><td width="15%"><b>Department</b></td><td width="20%"><b>NCDS Name</b></td></tr>${#foreach($custodianSupervisor in $custodianSupervisorList)<tr><td>${custodianSupervisor.custodianLastName}</td><td>${custodianSupervisor.custodianFirstName}</td><td>${custodianSupervisor.mapperId1}</td><td>${custodianSupervisor.custodianTitle}</td><td>${custodianSupervisor.custodianDept}</td><td>#if($custodianSupervisor.nonCustodianMedia)$custodianSupervisor.ncdsName}#end</td></tr>#end}</table><table><tr height="20px"><td></td></tr></table></td></tr></table><br/><table style="font-family:arial;font-size:11pt;"><tr><td valign="top">Legal Hold Escalation Notice:</td></tr></table><table style ="font-family:arial;font-size:11pt;"><tr><td valign="top">${legalHoldNotice}</td></tr></table><table style ="font-family:arial;font-size:11pt;margin-top:5px"><tr><td valign="top">#if($legalHoldMediaListAvailable)Preservation Data Sources:#end</td></tr><tr><td valign="top">#if($legalHoldMediaListAvailable)${#foreach( $media in $legalHoldMediaList )${media.mediaTypeName}<br/>#end}#end</td></tr></table><br/><br/>${defaultEmailLinks}<br/>' 
where notification_event_id=(select notification_event_id from notification_event where notification_event_name='Legal Hold is Escalated') and fusion_notification_id = (select fusion_notification_id from fusion_notification where fusion_notification_name = 'Default');
 
update dynamic_tags set expression = '<table width="100%" style="font-family:arial;font-size:11pt;margin-top:5px;"><tr><td valign="top">Custodian List:</td></tr><tr height="10px"><td></td></tr><tr><td valign="top"><table cellpadding="2" border="1" cellspacing="2" width="100%" style="font-family:arial;font-size:11pt;border:1px solid grey;"><tr><td width="20%"><b>Last Name</b></td><td width="20%"><b>First Name</b></td><td width="10%"><b>GUID</b></td><td width="15%"><b>Title</b></td><td width="15%"><b>Department</b></td><td width="20%"><b>NCDS Name</b></td></tr>${#foreach($custodianSupervisor in $custodianSupervisorList)<tr><td>${custodianSupervisor.custodianLastName}</td><td>${custodianSupervisor.custodianFirstName}</td><td>${custodianSupervisor.mapperId1}</td><td>${custodianSupervisor.custodianTitle}</td><td>${custodianSupervisor.custodianDept}</td><td>#if($custodianSupervisor.nonCustodianMedia)$custodianSupervisor.ncdsName}#end</td></tr>#end}</table><table><tr height="20px"><td></td></tr></table></td></tr></table>' where dynamic_tag_name = 'List of Supervisors';

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.6',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_COLLECTIONS' , 'All Collections' , 'All Collections' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_DATA_SOURCES' , 'All Data Sources' , 'All Data Sources' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_LABELS' , 'All Labels' , 'All Labels' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_FILE_EXTENSIONS' , 'All File Extensions' , 'All File Extensions' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_FILES' , 'All Files' , 'All Files' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_LANGUAGES' , 'All Languages' , 'All Languages' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ALL_CATEGORIES' , 'All Categories' , 'All Categories' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ID_AND_DATE' , 'ID and Date' , 'ID and Date' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'TYPE_AND_FILENAME' , 'Type and File Name' , 'Type and File Name' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'NEW_CODING_PANE' , 'New Coding Pane' , 'New Coding Pane' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'COLLECTION_INFORMATION' , 'Collection Information' , 'Collection Information' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SEARCH_PRODUCTION_ACTIVITIES' , 'Search Production Activities' , 'Search Production Activities' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'PRODUCTION_ACTIVITIES' , 'Production Activities' , 'Production Activities' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SEARCH_EXCLUSION_REPORT' , 'Search Exclusion Report' , 'Search Exclusion Report' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'FILTER_EMAIL_CONVERSATION_GRID' , 'Filter email conversation grid' , 'Filter email conversation grid' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'GENERATE_GRID' , 'Generate Grid' , 'Generate Grid' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'QUERY_FILE_LEVEL_HIT' , 'Query - File Level Hits' , 'Query - File Level Hits' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECTED_KEYWORDS' , 'Selected Keywords' , 'Selected Keywords' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'RELATED_TERMS' , 'Related Terms' , 'Related Terms' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'EXCLUDE' , 'Exclude' , 'Exclude' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ANY' , 'Any' , 'Any' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CLUSTERS' , 'CLUSTERS' , 'CLUSTERS' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DONE' , 'Done' , 'Done' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CLOSE_CONCEPT_ENGINE' , 'Close concept engine' , 'Close concept engine' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECTED_TERM' , 'Selected Term' , 'Selected Term' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CONCEPT_SEARCH' , 'CONCEPT SEARCH' , 'CONCEPT SEARCH' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ADD_TO_SAMPLE_SET' , 'Add to Sample Set' , 'Add to Sample Set' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'EXTERRO_QUERY_LANGUAGE' , 'Exterro Query Language (EQL)' , 'Exterro Query Language (EQL)' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'CONDITION' , 'Condition' , 'Condition' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SEARCH_REVIEWERS' , 'Search Reviewers' , 'Search Reviewers' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'MONTH' , 'Month' , 'Month' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'WEEK' , 'Week' , 'Week' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ENTER_VALID_DATE' , 'Enter a valid date. The Expected End Date copied from the request Due date has already passed.' , 'Enter a valid date. The Expected End Date copied from the request Due date has already passed.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

update property_info set Property_Desc = 'Defines the start day of the integration job' where Property_Name = 'HR_INTEGRATION_JOB_START_DAY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'Defines the start day of the integration job' where Property_Name = 'ASSET_INTEGRATION_JOB_START_DAY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'asset'));
update property_info set Property_Desc = 'Defines the start day of the integration job' where Property_Name = 'MATTER_INTEGRATION_JOB_START_DAY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'matter'));
update property_info set Property_Desc = 'Defines the start day of the integration job' where Property_Name = 'LDAP_INTEGRATION_JOB_START_DAY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'ldap'));

update property_info set Property_Desc = 'Defines the hourly frequency of the integration job' where Property_Name = 'HR_INTEGRATION_JOB_HOURLY_FREQUENCY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'hr'));
update property_info set Property_Desc = 'Defines the hourly frequency of the integration job' where Property_Name = 'ASSET_INTEGRATION_JOB_HOURLY_FREQUENCY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'asset'));
update property_info set Property_Desc = 'Defines the hourly frequency of the integration job' where Property_Name = 'MATTER_INTEGRATION_JOB_HOURLY_FREQUENCY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'matter'));
update property_info set Property_Desc = 'Defines the hourly frequency of the integration job' where Property_Name = 'LDAP_INTEGRATION_JOB_HOURLY_FREQUENCY' and Property_Group_Id = (Select Property_Group_Id from property_group where Property_Type_Id = (select Property_Type_Id FROM property_type where Property_Type_Name= 'ldap'));

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.7',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECT_CUSTODIAN_STATUS' , 'Select Custodian status' , 'Select Custodian status' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'SELECT_NCDS_STATUS' , 'Select NCDS status' , 'Select NCDS status' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'HTML' , 'HTML' , 'HTML' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ASSOCIATED_LABELS_CAMEL_CASE' , 'Associated Labels' , 'Associated Labels' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'GLOBAL_LABELS_CAMEL_CASE' , 'Global Labels' , 'Global Labels' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.0','5.0.10.8',CURRENT_TIMESTAMP);
GO
CREATE INDEX [IX_wf_ins_WF_Type_Object_Id] ON [workflow_instance] ([WF_Type_Id], [Object_Id])
GO
INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.8',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'TASK_ACTIVITIES_REPORT' , 'Task Activities Report' , 'Task Activities Report' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'REVIEW_REQUEST' , 'Review Request' , 'Review Request' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'LAST_COLLECTED_CC' , 'Last collected' , 'Last collected' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

Update Fusion_New_Label set Label_Display_Value = 'Concept Search' WHERE label_key = 'CONCEPT_SEARCH' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.9',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'FILE_COUNT_CC' , 'File count' , 'File count' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='labels');

Update Fusion_New_Label set Label_Display_Value = 'Name the project' WHERE label_key = 'NAME_THE_PROJECT' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');
Update Fusion_New_Label set Label_Display_Value = 'Enter project description' WHERE label_key = 'ENTER_PROJECT_DESCRIPTION' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');
Update Fusion_New_Label set Label_Display_Value = 'Requires approval?' WHERE label_key = 'REQUIRES_APPROVAL' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');
Update Fusion_New_Label set Label_Display_Value = 'Select project team' WHERE label_key = 'SELECT_PROJECT_TEAM' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');
Update Fusion_New_Label set Label_Display_Value = 'Expected end date' WHERE label_key = 'CREATE_PROJECT_END_DATE' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');
Update Fusion_New_Label set Label_Display_Value = 'Select request' WHERE label_key = 'SELECT_REQUEST' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.10',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'PROJECT_CANNOT_COMPLETE_AS_CONTAINS_OPEN_ISSUES' , 'Project cannot be completed, complete the open tasks associated with the project to complete the project.' , 'Project cannot be completed, complete the open tasks associated with the project to complete the project.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_CANNOT_COMPLETE_AS_CONTAINS_OPEN_ISSUES_WITH_ACTIVITY' , 'Deliverable cannot be completed, complete the open tasks associated with the activity to complete the deliverable.' , 'Deliverable cannot be completed, complete the open tasks associated with the activity to complete the deliverable.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'NONE_SELECTED_DS_AVAILABLE_FOR_SELECTED_CUSTODIANS' , 'None of the selected data sources are available for the selected custodians.' , 'None of the selected data sources are available for the selected custodians.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.11',CURRENT_TIMESTAMP);

Update Fusion_New_Label set Label_Display_Value = 'Cancel concept' WHERE label_key = 'CLOSE_CONCEPT_ENGINE' AND Fusion_Language_Id = (select Fusion_Language_Id from Fusion_Language where Language_Value = 'English') AND Label_Type_Id = (select Label_Type_Id from Label_Type where Label_Type_Name = 'labels');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.12',CURRENT_TIMESTAMP);

INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_SINGLE_DELIVERABLE_CUSTODIAN_REQUEST' , 'Are you sure you want to remove the custodian <custodian name> from the Request <Request name>.' , 'Are you sure you want to remove the custodian <custodian name> from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_MULTIPLE_DELIVERABLE_CUSTODIAN_REQUEST' , 'Are you sure you want to remove <n> custodians from the Request <Request name>.' , 'Are you sure you want to remove <n> custodians from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_MUlTIPLE_DELIVERABLE_CUSTODIAN_DATASOURCE_REQUEST' , 'Are you sure you want to remove <n> custodian datasource from the Request <Request name>.' , 'Are you sure you want to remove <n> custodian datasource from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_SINGLE_DELIVERABLE_CUSTODIAN_DATASOURCE_REQUEST' , 'Are you sure you want to remove <datasource name> datasource type of the custodian <custodian name> from the Request <Request name>.' , 'Are you sure you want to remove <datasource name> datasource type of the custodian <custodian name> from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_MULTIPLE_DELIVERABLE_NCDS_REQUEST' , 'Are you sure you want to remove <n> NCDS from the Request <Request name>.' , 'Are you sure you want to remove <n> NCDS from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'ARE_YOU_SURE_WANT_TO_REMOVE_SINGLE_DELIVERABLE_NCDS_REQUEST' , 'Are you sure you want to remove NCDS <name>  from the Request <Request name>.' , 'Are you sure you want to remove NCDS <name>  from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_CUSTODIAN_SINGLE_ROW_DELETE_MSG_REQUEST' , 'Custodian <deliverableNcdsName> has been removed from the Request <Request name>.' , 'Custodian <deliverableNcdsName> has been removed from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_CUSTODIAN_MULTIPLE_ROW_DELETE_MSG_REQUEST' , '<n> custodians have been removed from the Request  <Request name>.' , '<n> custodians have been removed from the Request  <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_NCDS_SINGLE_ROW_DELETE_MSG_REQUEST' , 'NCDS <deliverableNcdsName> has been removed from the Request <Request name>.' , 'NCDS <deliverableNcdsName> has been removed from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_NCDS_MULTIPLE_ROW_DELETE_MSG_REQUEST' , '<n> NCDS have been removed from the Request <Request name>.' , '<n> NCDS have been removed from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_CUSTODIAN_DATASOURCE_SINGLE_ROW_DELETE_MSG_REQUEST' , '<datasource name> datasource type  of the custodian <custodian name> has been removed from the Request <Request name>.' , '<datasource name> datasource type  of the custodian <custodian name> has been removed from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');
INSERT INTO Fusion_New_Label(fusion_language_id , label_key , label_base_value , label_display_value , label_type_id) ( SELECT FL.fusion_language_id , 'DELIVERABLE_CUSTODIAN_DATASOURCE_MULTIPLE_ROW_DELETE_MSG_REQUEST' , '<n> custodian datasource has been removed from the Request <Request name>.' , '<n> custodian datasource has been removed from the Request <Request name>.' , LT.label_type_id FROM fusion_language FL, label_type LT WHERE FL.language_value = 'English' AND LT.label_type_name='messages');

INSERT INTO db_version(Module_Name, Module_DDL_Version , Module_DML_Version , Created_Date_TS) VALUES ('core','5.0.10.1','5.0.10.13',CURRENT_TIMESTAMP);